### PR TITLE
US-1889327: Fixed suggestions to matrix-representation-of-transformations.md and types-of-coordinate-systems.md file

### PR DESCRIPTION
**Pull request by poojapoojari**
## Summary

Describe your changes here.

Fixes #Issue_Number (if available)

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet/docs-desktop?pullRequest=1265) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/docs-desktop?pullRequest=1265) before we can accept your contribution.<br/><br/>:x: poojapoojari [sign now](https://cla.dotnetfoundation.org/dotnet/docs-desktop?pullRequest=1265)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/docs-desktop?pullRequest=1265) it.</sub>

**Comment by poojapoojari** [comment]
@adegeo This PR is ready for technical review. Could you please review it?

Thank you!

**Comment by adegeo** [comment]
@poojapoojari Hi! Thank you so much for this PR, these changes look great! Do you want to flag this READY FOR REVIEW?

**Comment by adegeo** [comment]
Enabled READY FOR REVIEW per the email you had sent me. Thanks!

**Review by adegeo — APPROVED** [review]

**Pull request merged**
