### PR TITLE
Update componentresourcekey-markup-extension.md

### PR DESCRIPTION
**Pull request by griva89**
## Summary

Describe your changes here.

Fixes #Issue_Number (if available)

### CODE REVIEW

**Comment by adegeo** [comment]
Thank you for opening a PR! Do you have some more context around this change? According to the [API documentation](https://docs.microsoft.com/dotnet/api/system.windows.componentresourcekey.resourceid?view=net-5.0), it's correct as `ResourceId`

**Comment by griva89** [comment]
No I guess is just a typo

Il mar 2 feb 2021, 15:02 Andy De George <notifications@github.com> ha
scritto:

**Comment by adegeo** [comment]
OK. Well I'll close this issue then. Have a good day!

**Comment by griva89** [comment]
Great

Il gio 4 feb 2021, 17:44 Andy De George <notifications@github.com> ha
scritto:

**Pull request closed without merging**
