### PR TITLE
Add missing letter in first link of article

### LINKED ISSUE #66: 404 on first link in article for Dependency properties
The first link the the first sentence of the article points to a 404 link.

Sentence in question:
Windows Presentation Foundation (WPF) provides a set of services that can be used to extend the functionality of a type's **property**. 

**property** points to https://docs.microsoft.com/en-us/dotnet/standard/base-types/common-type-syste#properties instead of
https://docs.microsoft.com/en-us/dotnet/standard/base-types/common-type-syste**m**#properties

Regards,
Milos

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 73a26290-f551-b7c3-3677-426ea3fb39d9
* Version Independent ID: 8e6e4275-ed51-8425-7d6b-ee4a4b1c3fba
* Content: [Dependency properties overview - WPF .NET Framework](https://docs.microsoft.com/en-us/dotnet/desktop/wpf/advanced/dependency-properties-overview?view=netframeworkdesktop-4.8)
* Content Source: [dotnet-desktop-guide/framework/wpf/advanced/dependency-properties-overview.md](https://github.com/dotnet/docs-desktop/blob/live/dotnet-desktop-guide/framework/wpf/advanced/dependency-properties-overview.md)
* Product: **dotnet-framework**
* Technology: **dotnet-wpf**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

### PR DESCRIPTION
**Pull request by ignispotentia**
## Summary

Adds missing letter to the first link of the document.

Fixes #66

### CODE REVIEW

**Review by adegeo — APPROVED** [review]
Awesome, Thanks!

**Comment by adegeo** [comment]
@ignispotentia ACK! I just noticed this was pointing to the LIVE branch, this should be the MASTER branch. I'll revert this. 😿

**Comment by ignispotentia** [comment]
Didn't want to change anything, so I just took the default values that Github gave me when I edited 😂 it's probably my fault also a little bit.

**Comment by adegeo** [comment]
HRM yes I'll have to check that, it should have (in the issue opened) pointed to master.

**Comment by ignispotentia** [comment]
No worries, glad we found it out in time 😁

**Comment by adegeo** [comment]
Awesome. Found the config to adjust that so future comments appear to target the correct branch 😄  #70 thanks for forcing me to uncover that error hahaha.

**Comment by ignispotentia** [comment]
Awesome! And haha, considering the number of times MSDN docs helped me, this is the least I could do

**Pull request merged**
