### PR TITLE
Add WPF vs UWP Document

### PR DESCRIPTION
**Pull request by DeeJayTC**
## Summary

There are various differences between WPF and UWP when it comes to XAML. 
After a session i had just today and digging around someone created a nice list of differences which i updated
a litle bit. This would be some nice content to have in the docs. W

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet/docs-desktop?pullRequest=143) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/docs-desktop?pullRequest=143) before we can accept your contribution.<br/><br/>:x: DeeJayTC [sign now](https://cla.dotnetfoundation.org/dotnet/docs-desktop?pullRequest=143)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/docs-desktop?pullRequest=143) it.</sub>

**Comment by adegeo** [comment]
Thank you for this submission! There are some things to fix which the linter has pointed out. Also, the table content is generally formatted in markdown. I'll contact some UWP folks for review and also put this article through editing. Thanks again!

**Comment by adegeo** [comment]
@DeeJayTC I believe this submission violates rule #3 in the CLA you signed:

> Originality of Work. You represent that each of Your Submissions is entirely Your original work. Should You wish to Submit materials that are not Your original work, You may Submit them separately to the Project if You (a) retain all copyright and license information that was in the materials as You received them, (b) in the description accompanying Your Submission, include the phrase "Submission containing materials of a third party:" followed by the names of the third party and any licenses or other restrictions of which You are aware, and (c) follow any other instructions in the Project’s written guidelines concerning Submissions.

@sonnemaf I just noticed that you're the original author on this content submitted by a user. I was erroneously thinking that they were the author. If you're interested in having your list of differences processed and added to the WPF XAML documentation, please let me know and open up a PR.

I'm going to close this PR.

**Comment by DeeJayTC** [comment]
Yea accidently removed the source and license details, had them in my first commit. Never meant to sell it as my own work but really think its useful for a lot of people and should be in docs. :)

**Comment by adegeo** [comment]
No worries!

**Pull request closed without merging**
