### PR TITLE
Update index.md

### PR DESCRIPTION
**Pull request by bigboybamo**
## Summary

1. Made correction, Change "Froms" to "Forms"
2. Replaced .NET 7 with .NET 8

Contributes to  #1789

---

#### Internal previews

| 📄 File | 🔗 Preview link |
|:--|:--|
| [dotnet-desktop-guide/net/winforms/migration/index.md](https://github.com/dotnet/docs-desktop/blob/ffbba00f62cfed9a7ea72a2cca3d1a933e74c3ff/dotnet-desktop-guide/net/winforms/migration/index.md) | [How to upgrade a Windows Forms desktop app to .NET 7](https://review.learn.microsoft.com/en-us/dotnet/desktop/winforms/migration/index?branch=pr-en-us-1799&view=netdesktop-7.0) |

### CODE REVIEW

**Comment by bigboybamo** [comment]
@dotnet-policy-service agree

**Comment by adegeo** [comment]
Thanks!

Can you undo your changes from .NET 7 to .NET 8? There's more work to do in this before those changes can be made, which I can do next month:

- Update Visual Studio screenshots
- Update sample app from .NET 5 (ouch!) to .NET 8 (https://github.com/dotnet/samples/tree/main/windowsforms/matching-game/net5-windows

**Comment by bigboybamo** [comment]
@adegeo I have now reverted the .NET 8 changes back to 7

**Review by adegeo — APPROVED** [review]
Thanks!!

**Pull request merged**
