### PR TITLE
Add new OpenFolderDialog API article

### LINKED ISSUE #1676: Update page with OpenFolderDialog sample and reference
In WPF, we have added OpenFolderDialog - a common dialog to select folders. This dialog box will be available in .NET 8.

##### Here is a sample application demonstrating how to use, configure and show the dialog box
https://github.com/microsoft/WPF-Samples/blob/ab816cf24782cd8d1b19efa13077304ed8b1744c/Windows/CommonDialog/MainWindowViewModel.cs#L129-L161

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 720abfe3-7232-636f-20e7-d2c01db07d89
* Version Independent ID: cbdf3a5c-72a8-35c2-957a-f0a107319475
* Content: [How to open a common dialog box - WPF .NET](https://learn.microsoft.com/en-us/dotnet/desktop/wpf/windows/how-to-open-common-system-dialog-box?view=netdesktop-7.0)
* Content Source: [dotnet-desktop-guide/net/wpf/windows/how-to-open-common-system-dialog-box.md](https://github.com/dotnet/docs-desktop/blob/main/dotnet-desktop-guide/net/wpf/windows/how-to-open-common-system-dialog-box.md)
* Product: **dotnet-desktop**
* Technology: **dotnet-wpf**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

---
[Associated WorkItem - 143908](https://dev.azure.com/msft-skilling/Content/_workitems/edit/143908)

### PR DESCRIPTION
**Pull request by adegeo**
## Summary

- Update dialog screenshots for Win11
- Add OpenFileDialog section and code example
- Update project code to .NET 8

Fixes #1676

---

#### Internal previews

| 📄 File | 🔗 Preview link |
|:--|:--|
| [dotnet-desktop-guide/net/wpf/windows/dialog-boxes-overview.md](https://github.com/dotnet/docs-desktop/blob/9036c58c8c4ea68bae1fa2aec620f43ec4c8bd33/dotnet-desktop-guide/net/wpf/windows/dialog-boxes-overview.md) | [Dialog boxes overview (WPF .NET)](https://review.learn.microsoft.com/en-us/dotnet/desktop/wpf/windows/dialog-boxes-overview?branch=pr-en-us-1715&view=netdesktop-7.0) |
| [dotnet-desktop-guide/net/wpf/windows/how-to-open-common-system-dialog-box.md](https://github.com/dotnet/docs-desktop/blob/9036c58c8c4ea68bae1fa2aec620f43ec4c8bd33/dotnet-desktop-guide/net/wpf/windows/how-to-open-common-system-dialog-box.md) | [How to open a common dialog box (WPF .NET)](https://review.learn.microsoft.com/en-us/dotnet/desktop/wpf/windows/how-to-open-common-system-dialog-box?branch=pr-en-us-1715&view=netdesktop-7.0) |

### CODE REVIEW

**Comment by adegeo** [comment]
@dipeshmsft

**Review by dipeshmsft — APPROVED** [review]

**Comment by dipeshmsft** [comment]
> @dipeshmsft Do you want this published before .NET 8 releases?
Yes, I want this published before .NET 8 releases.

**Comment by adegeo** [comment]
@dipeshmsft And by that question, I was really asking if you want it published now? Sorry I wasn't clear.

**Comment by dipeshmsft** [comment]
> @dipeshmsft And by that question, I was really asking if you want it published now? Sorry I wasn't clear.

We can wait till GA for this.

**Pull request merged**
