### PR TITLE
Update layout-margins-padding-aligment-graphic3

### LINKED ISSUE #1606: The description provided for Orientation property of "StackPanel2" in the example is wrong.
The "StackPanel2" defined in the code has Orientation property assigned to "Vertical". But the TextBlock used to describe the StatckPanel orientation mentions "StackPanel.Orientation="Horizontal" which is wrong.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a01663b5-c69f-20d0-5d02-e216bd54565f
* Version Independent ID: a13e9d64-18ca-dc0e-0afe-211d921a98f6
* Content: [Alignment, Margins, and Padding Overview - WPF .NET Framework](https://learn.microsoft.com/en-us/dotnet/desktop/wpf/advanced/alignment-margins-and-padding-overview?view=netframeworkdesktop-4.8)
* Content Source: [dotnet-desktop-guide/framework/wpf/advanced/alignment-margins-and-padding-overview.md](https://github.com/dotnet/docs-desktop/blob/main/dotnet-desktop-guide/framework/wpf/advanced/alignment-margins-and-padding-overview.md)
* Product: **dotnet-framework**
* Technology: **dotnet-wpf**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

### PR DESCRIPTION
**Pull request by kgrems**
## Summary

Updated the layout-margins-padding-aligment-graphic3.png graphic to correct _StackPanel2_ saying that its orientation is "Horizontal" when it should be "Vertical."

Fixes #1606

### CODE REVIEW

**Review by adegeo — CHANGES_REQUESTED** [review]
Hi @kgrems thanks for helping out here! Sorry for the delay in getting back to you. I've been in/out on other projects and totally forgot to check in here.

The picture looks perfect! However, the source code in the article also needs to change so that the textbox matches the new screenshot.

**Comment by kgrems** [comment]
Thanks for the feedback!  I'll get right on it!

**Comment by adegeo** [comment]
If you need help figuring out where the code is, let me know. You'll have to update all of the languages for that code section, but considering that the fix is very minor, it should be an easy copy\paste operation. Thanks again!

**Comment by kgrems** [comment]
@dotnet-policy-service agree

**Comment by kgrems** [comment]
@adegeo Howdy!  I think I got the code samples cleaned up.  I was surprised that when I committed and pushed that it auto-added it to this pull request.  In other words, I thought I'd have to submit another pull request.  Guess not!

**Comment by adegeo** [comment]
Thanks! Because this pull request is between your fork and this one, when you make changes into the same branch used by this pull request, they'll be ingested automatically. If you made changes to a different branch, you would have to open another pull request between that new branch in your fork and the branch in this repository.

**Review by adegeo — APPROVED** [review]
Looks good!

**Comment by kgrems** [comment]
@adegeo  Nice!  I see something failed with the auto-merge.  Is this something I need to address?

**Comment by adegeo** [comment]
Pushing this PR through. The snippets testing error is related to these being in the old style and targeting old .NET Framework ;)

**Pull request merged**
