### PR TITLE
Content update - Add attached property snippet tests (user story 1878471)

### PR DESCRIPTION
**Pull request by v-trisshores**
@adegeo, this PR is ready for your review.

Update snippets for attached-properties-overview and how-to-register-an-attached-property.

[Internal review link](https://review.docs.microsoft.com/en-us/dotnet/desktop/wpf/properties/attached-properties-overview?view=netdesktop-5.0&branch=pr-en-us-1224) for article.

### CODE REVIEW

**Comment by adegeo** [comment]
Hi Tris! What is this PR for exactly? This will alter the code sample being referenced in the article, changing the base class from `DependencyObject` to `UIElement`. `DependencyObject` is specifically called out in the article as a prerequisite to attached properties.

**Comment by v-trisshores** [comment]
The article states: "follow the WPF model of having an attached property also be a dependency property, by deriving your class from DependencyObject." It doesn't say derive *directly* from DependencyObject.

Per [UiElement](https://docs.microsoft.com/en-us/dotnet/api/system.windows.uielement?view=windowsdesktop-6.0) docs, UiElement derives from DependencyObject:
image

If the Aquarium example derives directly from DependencyObject, the build will properly fail, as a result of the new snippet validation test code.

**Comment by adegeo** [comment]
I guess my only issue with this is that we're speaking (usually) to people who don't really know much about WPF and how this system works. Maybe the example should be simplified if it requires using a derived type such as `UIElement`. The `UIElement` concept is potentially unknown to the reader at the time they read this article.

**Comment by v-trisshores** [comment]
@adegeo, the .NET Framework 4.0 article as well as the 6.0 version use UIElement in the snippet. UIElement is explained in both versions of the article: "The target type can be more specific than object. For example, the DockPanel.GetDock accessor method types the target as UIElement because the attached property is intended to be set on UIElement instances." To make that even clearer, I've added "UiElement indirectly derives from DependencyObject".

Revisiting this article, I see an issue that stemmed from the .NET Framework 4.0 version. That version says "The signature for the GetPropertyName accessor must be: public static object GetPropertyName(object target)". Actually, the signature must be "public static object GetPropertyName(DependencyObject target)", because GetValue and SetValue are DependencyObject methods, not Object methods. I've updated the .NET 6.0 article accordingly.

I propose we leave the snippet as-is but add the extra article clarification and update accessor signatures (done in this PR). If you still want me to change UIElement to Dependency property, I'll make that change as well. This PR updates the .NET 6.0 article+snippet only.

**Review by adegeo — APPROVED** [review]
I like your changes. Thanks!

**Comment by v-trisshores** [comment]
@adegeo, thank you.

**Pull request merged**
