### PR TITLE
Update printpreviewdialog-control-overview-windows-forms.md

### PR DESCRIPTION
**Pull request by Tanya-Solyanik**
Added clarification. 

## Summary

Related to https://github.com/dotnet/docs-desktop/issues/1546, question 3

### CODE REVIEW

**Comment by Tanya-Solyanik** [comment]
The error does not point to any violations in the md file, but complains about a missing package

+ markdownlint-cli@0.33.0
added 27 packages from 21 contributors in 1.37s
internal/modules/cjs/loader.js:818
  throw err;
  ^

Error: Cannot find module 'node:fs'
Require stack:
- /opt/hostedtoolcache/node/12.22.12/x64/lib/node_modules/markdownlint-cli/markdownlint.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/opt/hostedtoolcache/node/12.22.12/x64/lib/node_modules/markdownlint-cli/markdownlint.js:5:12)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:[14](https://github.com/dotnet/docs-desktop/actions/runs/3972796744/jobs/6811005521#step:4:15))
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/opt/hostedtoolcache/node/12.[22](https://github.com/dotnet/docs-desktop/actions/runs/3972796744/jobs/6811005521#step:4:23).12/x64/lib/node_modules/markdownlint-cli/markdownlint.js'
  ]
}

**Comment by Tanya-Solyanik** [comment]
@adegeo - Could you please help with the lint failure?

**Review by merriemcgaw — APPROVED** [review]
lgtm

**Pull request merged**
